version: "3"

services:
  api:
    container_name: pacmen_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
      - 8001:8001
    restart: unless-stopped

  client:
    container_name: pacmen_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: [ "npm", "run", "start" ]
    restart: unless-stopped
