version: '3'

services:
  pacmen-harness-client:
    container_name: pacmen-harness-client
    build:
      context: ../client

  pacmen-harness-api:
    container_name: pacmen-harness-api
    build:
      context: ../api

  pacmen-harness-db:
    container_name: pacmen-harness-db
    image: postgres:latest
    environment:
      POSTGRES_USER: pacmen
      POSTGRES_PASSWORD: pacmen
      POSTGRES_DB: pacmen
    volumes:
      - ../api/schema.sql:/docker-entrypoint-initdb.d/schema.sql