version: '3'

services:
  harness_db:
    container_name: harness_db
    image: postgres:latest
    environment:
      POSTGRES_USER: harness
      POSTGRES_PASSWORD: harness
      POSTGRES_DB: harness
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  harness_docker_api:
    container_name: harness_docker_api
    build: ../docker-api
    ports:
      - "5000:5000"
    volumes:
      - ../docker-api:/app/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TRAEFIK_HOST=localhost
      - TRAEFIK_PORT=80

  harness_traefik:
    container_name: harness_traefik
    image: traefik:v2.11
    command: 
      - --api.insecure=true 
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
      name: pacmen-harness_default