name: Pacmen Coding Competition Harness
run-name: ${{ github.actor }} is deploying 🚀
on:
  push:
    branches:
      - main



jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Images
        run: |
          cd ops
          docker compose build

  Deploy:
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Production
        run: |
          cd ops
          docker compose --env-file .env.prod up -d
